### ISSUE TITLE
TensorFlow 2.14.0 Fails to Detect GPU on Google Colab with CUDA 12.2

### ISSUE THREAD

**Issue by Trulatriz** [z-mahmud22/Mask-RCNN_TF2.14.0#20]
I'm experiencing an issue where TensorFlow 2.14.0 is unable to detect the GPU on Google Colab. I verified that a GPU (NVIDIA A100-SXM4-40GB) is available using nvidia-smi, which shows CUDA version 12.2. However, when I run the code to list physical devices in TensorFlow:

import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

The output is always Num GPUs Available: 0.

The details are as follows:

Google Colab environment.
TensorFlow version: 2.14.0.
CUDA version on Colab: 12.2 (as shown by nvidia-smi).
Python version: 3.10.12

Could this be an issue related to the compatibility of TensorFlow 2.14.0 with CUDA 12.2? If so, what would be the solution?

Any guidance would be greatly appreciated.

**Comment by z-mahmud22** [comment]
Hi @Trulatriz. sorry for my late response. 

Your guess is right. The issue is that TensorFlow 2.14 is [not compatible](https://www.tensorflow.org/install/source#gpu) with CUDA 12.2. 

However, the good news is that you can still use this codebase on Google Colab. Please follow these steps: 
1. Remove any existing CUDA installation via: 
```
!sudo apt-get --allow-change-held-packages --purge remove "*cublas*" "cuda*" "nsight*"
```
2. Install CUDA 11.8 via: 
```
!wget https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_520.61.05_linux.run
!chmod +x cuda_11.8.0_520.61.05_linux.run
!./cuda_11.8.0_520.61.05_linux.run --silent --toolkit
```
3. Set environment variables to point to the new CUDA installation:
```
import os
os.environ['PATH'] = "/usr/local/cuda-11.8/bin:" + os.environ['PATH']
os.environ['CUDA_HOME'] = "/usr/local/cuda-11.8"
os.environ['LD_LIBRARY_PATH'] = "/usr/local/cuda-11.8/lib64:" + os.environ.get('LD_LIBRARY_PATH', '')
```
4. Verify CUDA compiler via: `!nvcc --version` which should print: 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

If you successfully follow the steps above, you'll be able to downgrade to Cuda 11.8 on Google Colab or any machine running Ubuntu 22.04 OS. Then re-install the required libraries for this codebase via: 
```
!pip3 install -r requirements.txt # These installations will automatically uninstall the current TF and other existing libraries
```
Finally, you can check if TensorFlow is using the GPU via: `print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))` OR if Mask-RCNN model is loaded in the GPU as suggested in my [StackOverflow answer](https://stackoverflow.com/a/77504039/12317368).
